{
 "title": "Story Grafana by Empirex",
 "description": "Story Metrics",
 "tags": [
  "Blockchain",
  "Cosmos"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   { "name": "chain_id", "label": "Chain ID", "query": "iliad-0" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({chain_id=\"$chain_id\"},instance)"
    }
   },
   {
    "name": "validator",
    "query": "3EFC18878454304004F18E8B3BFF7BC8ED166D10"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Logo",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; align-items: center; height: 100%;\">\n  <img src=\"https://empirex.netlify.app/Logo%20Files/For%20Web/png/White%20logo%20-%20no%20background.png\" alt=\"Empirex Image\" style=\"max-width: 80%; max-height: 300px; height: auto;\" />\n</div>\n"
   }
  },
  {
   "title": "Chain Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_interval_seconds_count{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Gas Used",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "cosmos_tx_gas_used", "legendFormat": "Active" }
   ]
  },
  {
   "title": "Consensus Block Creation Frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_interval_seconds_count",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{chain_id=\"$chain_id\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "cometbft_consensus_missing_validators{chain_id=\"$chain_id\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "cometbft_consensus_byzantine_validators{chain_id=\"$chain_id\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{chain_id=\"$chain_id\"}",
     "legendFormat": "Online"
    },
    {
     "expr": "cometbft_consensus_missing_validators_power{chain_id=\"$chain_id\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "cometbft_consensus_byzantine_validators_power{chain_id=\"$chain_id\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{chain_id=\"$chain_id\"}",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{chain_id=\"$chain_id\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Instance Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Network Input",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "cometbft_p2p_peer_receive_bytes_total{chain_id=\"$chain_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total Network Output",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "cometbft_p2p_peer_send_bytes_total{chain_id=\"$chain_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}